server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /mfx-admin/index.html;

        # 核心：禁止 index.html 缓存，确保每次加载都是最新的
        if ($request_uri ~* .*/index.html$) {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires "0";
        }
        # 针对根路径访问也禁止缓存
        if ($request_uri ~* ^/?$) {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires "0";
        }

        # 确保正确的 MIME 类型
        types {
            application/javascript js mjs;
            text/css css;
            text/html html;
        }
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
